### ISSUE TITLE
trollius is required (but shouldn't be?)

### ISSUE THREAD

**Issue by gerkey** [osrf/osrf_pycommon#12]
Without trollius installed, ament gives me this error:

~~~
$ ament
Traceback (most recent call last):
 File "/home/gerkey/ros2_ws/install/bin/ament", line 5, in <module>
   from pkg_resources import load_entry_point
 File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 3084, in <module>
   @_call_aside
 File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 3070, in _call_aside
   f(*args, **kwargs)
 File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
   working_set = WorkingSet._build_master()
 File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
   ws.require(__requires__)
 File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 952, in require
   needed = self.resolve(parse_requirements(requirements))
 File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 839, in resolve
   raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'trollius' distribution was not found and is required by osrf-pycommon
~~~

If I `sudo pip3 install trollius`, then the error goes away and ament works.  I would add that line to the installation page, but @dirk-thomas says that it should work without trollius.

**Comment by wjwwood** [comment]
https://github.com/osrf/osrf_pycommon/pull/13
