### ISSUE TITLE
import of termios fails on Windows testings

### ISSUE THREAD

**Issue by wjwwood** [osrf/osrf_pycommon#16]
See: http://ci.ros2.org/job/ros2_batch_ci_windows/662/testReport/nose.failure/Failure/runTest/
```
Traceback (most recent call last):
  File "C:\tools\python\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\tools\python\lib\unittest\case.py", line 577, in run
    testMethod()
  File "C:\tools\python\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\tools\python\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\tools\python\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\tools\python\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\tools\python\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\tools\python\lib\imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Jenkins\workspace\ros2_batch_ci_windows\workspace\src\ament\osrf_pycommon\osrf_pycommon\process_utils\execute_process_pty.py", line 16, in <module>
    import pty
  File "C:\tools\python\lib\pty.py", line 11, in <module>
    import tty
  File "C:\tools\python\lib\tty.py", line 5, in <module>
    from termios import *
ImportError: No module named 'termios'
```

**Comment by wjwwood** [comment]
Fixed with 519dbf76fed941c1be6c2c1de9a60539254f44ca
