### ISSUE TITLE
Broken with python-flake8-3.0.4

### ISSUE THREAD

**Issue by cottsay** [osrf/osrf_pycommon#28]
Fedora is moving to flake8 3.0.4 in Fedora 26, and it looks like this package isn't clean. Even after applying a317efbb9e28f72881b81a9bf782be30f2cc7fbb, I see the following test failure:

```
nosetests-2.7 -w tests
...............................F
======================================================================
FAIL: Test source code for pyFlakes and PEP8 conformance
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/osrf_pycommon-0.1.2/tests/test_code_format.py", line 18, in test_flake8
    "Command '{0}' returned non-zero exit code '{1}'".format(' '.join(cmd), p.returncode)
AssertionError: Command 'flake8 /builddir/build/BUILD/osrf_pycommon-0.1.2/tests/../osrf_pycommon --count --exclude=*async_execute_process_asyncio/impl.py' returned non-zero exit code '1'
-------------------- >> begin captured stdout << ---------------------
/builddir/build/BUILD/osrf_pycommon-0.1.2/tests/../osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py:42:41: E901 SyntaxError: invalid syntax
1


--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 32 tests in 1.025s

FAILED (failures=1)
```

Initial build failure: http://koji.fedoraproject.org/koji/taskinfo?taskID=15695961
Downstream bug: https://bugzilla.redhat.com/1377139

Thanks,

--scott

**Comment by jpgr87** [comment]
It looks like the exclude path isn't working.  The test's cwd is parallel to the source files being tested, so the exclude path relative to the cwd won't catch the source file.  Changing it to `--exclude=../*async_execute_process_asyncio/impl.py./*async_execute_process_asyncio/impl.py` seems to fix it.  A better option may be to join the `source_dir` to the beginning of the exclude glob to make sure the relative paths are right.

**Comment by wjwwood** [comment]
@jpgr87 I assume you're using master branch or somehow have the patch to use the command line interface of flake8 that @cottsay mentioned above?

**Comment by jpgr87** [comment]
Yes, I applied a317efb to the 0.1.2 release, as @cottsay described.

**Comment by wjwwood** [comment]
Could either of you try https://github.com/osrf/osrf_pycommon/pull/32 to see if it addresses the issue? I was unable to reproduce it on my machine.

**Comment by jpgr87** [comment]
I tested the `fix_exclude` branch, it does resolve the issue we're seeing:

```
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
$ nosetests -w tests/
...............................F
======================================================================
FAIL: Test source code for pyFlakes and PEP8 conformance
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rich/Source/osrf_pycommon/tests/test_code_format.py", line 26, in test_flake8
    "Command '{0}' returned non-zero exit code '{1}'".format(' '.join(cmd), p.returncode)
AssertionError: Command '/usr/bin/python2 -m flake8 /home/rich/Source/osrf_pycommon/tests/../osrf_pycommon --count --jobs 1 --exclude=*async_execute_process_asyncio/impl.py' returned non-zero exit code '1'
-------------------- >> begin captured stdout << ---------------------
/home/rich/Source/osrf_pycommon/tests/../osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py:42:41: E901 SyntaxError: invalid syntax
1


--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 32 tests in 1.506s

FAILED (failures=1)
$ git checkout fix_exclude 
Switched to branch 'fix_exclude'
Your branch is up-to-date with 'origin/fix_exclude'.
$ nosetests -w tests/
................................
----------------------------------------------------------------------
Ran 32 tests in 1.496s

OK
[rich@ osrf_pycommon]$ 
```


Did you add `-w tests/` when testing on your machine?  We're using that flag, which changes the working directory such that the exclude path isn't valid (wheras it is valid when your working directory is the source root)

**Comment by wjwwood** [comment]
No, I do not use the `-w tests/` option when I test it locally (or on travis, or on the ROS 2 build farm). But this new way is more robust.

**Comment by wjwwood** [comment]
Thanks for testing.
