### ISSUE TITLE
PyPI archive missing async_execute_process_asyncio module

### ISSUE THREAD

**Issue by kartikmohta** [osrf/osrf_pycommon#37]
Was trying to install the package on Arch using pip (python 3.6.1) but looks like the archive on PyPI is missing the `async_execute_process_asyncio` module. There is no such folder present in `process_utils`.

**Comment by wjwwood** [comment]
I tried to reproduce this on my machine and I could not. Are there any other details you can give?

**Comment by kartikmohta** [comment]
If you download the archive from https://pypi.python.org/pypi/osrf_pycommon/0.1.2 and check the files inside, it is missing the `async_execute_process_asyncio` module.

**Comment by wjwwood** [comment]
What I meant was, are you getting an error when installing from `pip`? I understand what you're saying about the archive, but that package is not used by Python2 at all, only Python3. So that might be why it is happening. I will try to fix the archive on pypi, but I want to understand why you're seeing an issue but others are not.

**Comment by wjwwood** [comment]
I fixed this in bdcca33, I'll try to fix the pypi upload without a new release, but I might just need to release it again.

I'm still curious to how you noticed and why others had not seen this issue before now.

**Comment by wjwwood** [comment]
I had to release `0.1.3`, but it should be fixed now 👍.

**Comment by kartikmohta** [comment]
I saw it because

> Was trying to install the package on Arch using pip (python 3.6.1)

🙂

**Comment by wjwwood** [comment]
I understand "why" you saw it. What I was hoping to see was the actual error, was it "file not found", "could not import", or something else? How did you install it, did you just run `pip install osrf_pycommon` or did you download the source archive and run `pip install path/to/osrf_pycommon.tar.gz`?

Lots of other people and processes install it using pip and don't have a problem. I'm wondering if it is based on you using Arch or the process you were using.

**Comment by kartikmohta** [comment]
I got the following error when running `catkin_tools` with the previous version:
```
$ sudo pip install osrf_pycommon==0.1.2
Collecting osrf_pycommon==0.1.2
  Downloading osrf_pycommon-0.1.2.tar.gz
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from osrf_pycommon==0.1.2)
Installing collected packages: osrf-pycommon
  Running setup.py install for osrf-pycommon ... done
Successfully installed osrf-pycommon-0.1.2
$ catkin
Traceback (most recent call last):
  File "/usr/bin/catkin", line 11, in <module>
    load_entry_point('catkin-tools==0.4.4', 'console_scripts', 'catkin')()
  File "/usr/lib/python3.6/site-packages/catkin_tools/commands/catkin.py", line 267, in main
    catkin_main(sysargs)
  File "/usr/lib/python3.6/site-packages/catkin_tools/commands/catkin.py", line 166, in catkin_main
    argument_preprocessors = create_subparsers(parser, verbs)
  File "/usr/lib/python3.6/site-packages/catkin_tools/commands/catkin.py", line 58, in create_subparsers
    desc = load_verb_description(verb)
  File "/usr/lib/python3.6/site-packages/catkin_tools/commands/catkin.py", line 45, in load_verb_description
    return entry_point.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/catkin_tools/verbs/catkin_build/__init__.py", line 17, in <module>
    from .cli import main
  File "/usr/lib/python3.6/site-packages/catkin_tools/verbs/catkin_build/cli.py", line 47, in <module>
    from catkin_tools.context import Context
  File "/usr/lib/python3.6/site-packages/catkin_tools/context.py", line 32, in <module>
    from .resultspace import get_resultspace_environment
  File "/usr/lib/python3.6/site-packages/catkin_tools/resultspace.py", line 30, in <module>
    from osrf_pycommon.process_utils import execute_process
  File "/usr/lib/python3.6/site-packages/osrf_pycommon/process_utils/__init__.py", line 20, in <module>
    from .async_execute_process import async_execute_process
  File "/usr/lib/python3.6/site-packages/osrf_pycommon/process_utils/async_execute_process.py", line 22, in <module>
    from .async_execute_process_asyncio import async_execute_process
ModuleNotFoundError: No module named 'osrf_pycommon.process_utils.async_execute_process_asyncio'
```
This is fixed with the 0.1.3 version.

**Comment by wjwwood** [comment]
That's what I was looking for, the reason it affected you because you had the unique situation of:

- using catkin_tools with
- python3
- and installing from pip

No other use case matched those parameters thus far.

**Comment by kartikmohta** [comment]
Yeah, had to make some changes in `catkin_tools` as well to make it work with Python 3. Thanks for fixing it 🙂
