### ISSUE TITLE
missing dependency declaration on python mock

### ISSUE THREAD

**Issue by wjwwood** [osrf/osrf_pycommon#49]
I had to disable the dev job on the ros2 build farm (https://github.com/ros2/rosdistro/pull/109), because `mock` is not found during the job, e.g.:

```
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  arguments, _, _, defaults = inspect.getargspec(func)
/tmp/catkin_workspace/src/osrf_pycommon/tests/unit/test_cli_utils/test_verb_pattern.py:69: DeprecationWarning: Please use assertRaisesRegex instead.
  with self.assertRaisesRegexp(ValueError, 'one or two parameters'):
/tmp/catkin_workspace/src/osrf_pycommon/osrf_pycommon/cli_utils/verb_pattern.py:55: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  ', '.join(inspect.getargspec(func)[0])))
ok
test_split_arguments_by_verb (tests.unit.test_cli_utils.test_verb_pattern.TestCliUtilsVerbPattern) ... ok

======================================================================
ERROR: test_terminal_utils (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_terminal_utils
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/catkin_workspace/src/osrf_pycommon/tests/unit/test_terminal_utils.py", line 1, in <module>
    import mock
ModuleNotFoundError: No module named 'mock'


----------------------------------------------------------------------
Ran 29 tests in 0.297s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=29 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=29 errors=1 failures=0>
---
Failed   <<< osrf_pycommon      [ Exited with code 1 ]

Summary: 0 packages finished [0.90s]
  1 package failed: osrf_pycommon
  1 package had stderr output: osrf_pycommon
```
-- from http://build.ros2.org/job/Bdev__osrf_pycommon__ubuntu_bionic_amd64/1/

**Comment by mikaelarguedas** [comment]
fixed in https://github.com/osrf/osrf_pycommon/pull/50

**Comment by aswinthomas** [comment]
This somehow does not do the fix for me.

To resolve deps I run
```
rosdep install --from-paths src --ignore-src --rosdistro crystal -y -r
```

```
echo $ROS_PYTHON_VERSION
3
```
If I remove the condition ```condition="$ROS_PYTHON_VERSION == 3"``` it works, which means this condition is false on my laptop when validated.

Im using Ubuntu 16.04 and compiling from latest source

**Comment by aswinthomas** [comment]
Fixed. Possibly due to sourcing multiple workspaces.
