### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by agaertner** [osrf/osrf_pycommon#90]
```
[ERROR] [Planner.py-4]: exception occurred while executing process:
Traceback (most recent call last):
  File "F:\ros2\ros2_humble\install\Lib\site-packages\launch\actions\execute_local.py", line 546, in __execute_process
    transport, self._subprocess_protocol = await async_execute_process(
  File "F:\ros2\ros2_humble\install\Lib\site-packages\osrf_pycommon\process_utils\async_execute_process_asyncio\impl.py", line 135, in async_execute_process
    transport, protocol = await _async_execute_process_pty(
  File "F:\ros2\ros2_humble\install\Lib\site-packages\osrf_pycommon\process_utils\async_execute_process_asyncio\impl.py", line 45, in _async_execute_process_nopty
    transport, protocol = await loop.subprocess_exec(
  File "c:\python38\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "c:\python38\lib\asyncio\windows_events.py", line 385, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "c:\python38\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "c:\python38\lib\asyncio\windows_events.py", line 881, in _start
    self._proc = windows_utils.Popen(
  File "c:\python38\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "c:\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```

I am getting this error in all my ROS packages. Research suggest that shell has to be explicitely passed in a subprocess call, but none of my packages actually do this call but the logs always reference ``osrf_pycommon`` so I am posting it here for awareness.
Ref. <https://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application>

**Comment by cottsay** [comment]
A couple of thoughts:
1. The backtrace originates in `launch`. It's likely that the problem originates there as well.
2. We need more information to debug the problem. In particular, it would be good to know what launch operation is being attempted.
